# Generated by Django 4.1.1 on 2022-09-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='city',
            field=models.TextField(default='Bogota', max_length=250),
        ),
    ]
