# Generated by Django 4.1.1 on 2022-09-21 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_hour',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
