# Generated by Django 4.1.1 on 2022-09-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking_booking_hour_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_hour',
        ),
    ]
